  const baseUrl = 'http://localhost:8080/api'
  export const healthApiUrl = 'http://localhost:8080/api/health';
  export const todoApiUrl = 'http://localhost:8080/api/todos';
  export const userApiUrl = 'http://localhost:8080/api/users';
  export const settingsApiUrl = 'http://localhost:8080/api/settings';
  export const gamificationApiUrl = 'http://localhost:8080/api/gamification'
  export const bulkApiUrl = `${baseUrl}/todos/bulk`
  export const noteApiUrl = `${baseUrl}/notes`
  export const projectApiUrl = `${baseUrl}/projects`
  export const aiPredictionApiUrl = `${baseUrl}/ai/predict`
  export const aiPredictionEffortUrl = `${baseUrl}/ai/predict-effort`
  export const milestoneApiUrl = `${baseUrl}/milestones`
  export const teamApiUrl = `${baseUrl}/teams`
  export const smartPlannerUrl =`${baseUrl}/ai/planner/recommend`
  export const smartPlannerFeedbackUrl = `${baseUrl}/ai/planner/feedback`; 
  export const getAiMilestonesUrl = `${baseUrl}/projects/suggest`;
  export const trackAiMilestoneSelectionUrl = `${baseUrl}/projects/track-selection`;
  export const trackAiMilestoneDegradationUrl = `${baseUrl}/projects/track-degradation`;
  export const trackAiIgnoredMilestoneUrl = `${baseUrl}/projects/track-ignorance`;
  export const aiNotePredictionUrl = `${baseUrl}/ai/notes/predict`;
  export const aiCategoriesApiUrl = `${baseUrl}/ai/todos/categories`;
  export const aiNoteCategoriesUrl = `${baseUrl}/ai/notes/categories`;
  export const streakUrl = `${baseUrl}/streaks/sync`;
  export const aiTodoSnoozingUrl = `${baseUrl}/ai/planner/snooze`;
  export const departmentApiUrl = `${baseUrl}/departments`
  export const allUsersAdminApiUrl = `${teamApiUrl}/all-users`;
  export const MasterDataUrl = `${baseUrl}/masterdata`
  export const InvitationUrl = `${baseUrl}/invitation`

  
